services:

  postgres:
    image: postgres:17
    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SqlPgAdmin
      POSTGRES_DB: product_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d product_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  redis:
    image: redis:8-alpine
    container_name: redis_server

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data


  fastapi:
    build: .
    container_name: product_api

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:SqlPgAdmin@postgres:5432/product_db
      REDIS_HOST: redis

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  celery:
    build: .
    container_name: celery_worker

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:SqlPgAdmin@postgres:5432/product_db
      REDIS_HOST: redis

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

    command: celery -A app.celery_worker.celery worker --loglevel=info


  flower:
    build: .
    container_name: flower

    depends_on:
      - redis
      - celery

    ports:
      - "5555:5555"

    environment:
      REDIS_HOST: redis

    command: celery -A app.celery_worker.celery flower --port=5555


volumes:
  postgres_data:
  redis_data: