services:

  redis:
    image: redis:8-alpine
    container_name: redis_server


    volumes:
      - redis_data:/data


  fastapi:
    build: .
    container_name: product_api

    ports:
      - "127.0.0.1:8000:8000"

    depends_on:
      redis:
        condition: service_started

    volumes:
      - .:/app

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


  celery:
    build: .
    container_name: celery_worker

    depends_on:
      redis:
        condition: service_started

    volumes:
      - .:/app

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

    command: celery -A app.celery_worker.celery worker --loglevel=info


  flower:
    build: .
    container_name: flower

    depends_on:
      - redis
      - celery

    ports:
      - "5555:5555"

    environment:
      REDIS_HOST: redis

    command: celery -A app.celery_worker.celery flower --port=5555


volumes:
  postgres_data:
  redis_data:
